services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: devel
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    volumes:
      - test_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U odoo -d devel"]
      interval: 10s
      timeout: 5s
      retries: 5

  odoo_proxy:
    image: odoo:16.0
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "16069:16069"
    environment:
      HOST: db
      USER: odoo
      PASSWORD: odoo
    command:
      [
        "odoo",
        "--database=devel",
        "--http-port=16069",
        "--init=crm",
        "--without-demo=all",
      ]
    volumes:
      - test_odoo_data:/var/lib/odoo

volumes:
  test_postgres_data:
  test_odoo_data:
